### PR TITLE
Add SublimeText3 support

### PR DESCRIPTION
**Pull request by unai-ndz**
Using a json file to set the possible options was the best way I could find. The theming in sublime text is pretty extensive.

### CODE REVIEW

**Comment by unai-ndz** [comment]
* Just thought it would be better to keep them in one option but I can split them.

* Yeah, I will make it a path, it's much better that way.

* I tried with serde but it's JSON with comments, out of the spec, so serde won't [parse](https://github.com/serde-rs/json/issues/168) it. It was a real bummer to find out. There is a [crate](https://github.com/hjson/hjson-rust/) for HJSON but it's not very active. It can be worth it though because VSCode uses JSON with comments and I plan to add a PR for that soon.

**Comment by nicohman** [comment]
It looks like the sublime text default Preferences.sublime-settings's comments are just `//`s on a single line, so if you could just filter out any line that contains `//`, then parse it with serde, it would probably work. Maybe try that?

**Comment by unai-ndz** [comment]
On the default yes, but we would erase any comments left by the user too. Testing a theme on ravenserver could mean losing all your comments.

**Comment by nicohman** [comment]
Just cull comments, then parse, then append the culled comments to the end of the file? While it is a bit hacky, I think it should work fine.

**Comment by unai-ndz** [comment]
I have splitted the options and fixed the parsing. If you won't accept either the manual parsing or the HJSON crate I will cull the comments as you said but I don't think that's a good aproach. Comments without his position lose a lot of meaning.

**Comment by nicohman** [comment]
Alright then, looks good. I suppose there really isn't a better way to handle it. Thanks for the pull request!

**Pull request merged**
